/*
Código Fuente: sustantivosPlurales.pl
Desarrolado por: Saymon Astúa, Oscar Araya
Tarea 2 - Lenguajes
IS 2020 - Grupo 01

Descripción: Base de datos de los sustantivos en forma plural
Instituto Tecnológico de Costa Rica | CE3104 - Lenguajes, Compiladores e Interpretes
*/


sustantivo(plural, masculino, ["esos"], ["those"]).
sustantivo(plural, femenino, ["esas"], ["those"]).
sustantivo(plural, femenino, ["acciones"], ["actions"]).
sustantivo(plural, femenino, ["sistemas"], ["systems"]).
sustantivo(plural, femenino, ["edades"], ["ages"]).
sustantivo(plural, masculino, ["aires"], ["airs"]).
sustantivo(plural, masculino, ["patrones"], ["patterns"]).
sustantivo(plural, masculino, ["expertos"], ["experts"]).
sustantivo(plural, masculino, ["teoremas"], ["theorems"]).
sustantivo(plural, masculino, ["árboles"], ["trees"]).
sustantivo(plural, masculino, ["animales"], ["animals"]).
sustantivo(plural, femenino, ["respuestas"], ["answers"]).
sustantivo(plural, femenino, ["manzanas"], ["apples"]).
sustantivo(plural, masculino, ["artes"], ["arts"]).
sustantivo(plural, masculino, ["bebés"], ["babies"]).
sustantivo(plural, femenino, ["espaldas"], ["backs"]).
sustantivo(plural, femenino, ["bolas"], ["balls"]).
sustantivo(plural, femenino, ["pelotas"], ["balls"]).
sustantivo(plural, masculino, ["bancos"], ["banks"]).
sustantivo(plural, femenino, ["camas"], ["beds"]).
sustantivo(plural, masculino, ["pájaros"], ["birds"]).
sustantivo(plural, masculino, ["barcos"], ["boats"]).
sustantivo(plural, masculino, ["cuerpos"], ["bodies"]).
sustantivo(plural, masculino, ["huesos"], ["bones"]).
sustantivo(plural, masculino, ["libros"], ["books"]).
sustantivo(plural, femenino, ["cajas"], ["boxes"]).
sustantivo(plural, femenino, ["energías"], ["energies"]).
sustantivo(plural, masculino, ["ejemplos"], ["examples"]).
sustantivo(plural, femenino, ["experiencias"], ["experiences"]).
sustantivo(plural, masculino, ["ojos"], ["eyes"]).
sustantivo(plural, masculino, ["juegos"], ["games"]).
sustantivo(plural, femenino, ["chicas"], ["girls"]).
sustantivo(plural, femenino, ["niñas"], ["girls"]).
sustantivo(plural, masculino, ["vidrios"], ["glasses"]).
sustantivo(plural, masculino, ["gobiernos"], ["governments"]).
sustantivo(plural, masculino, ["grupos"], ["groups"]).
sustantivo(plural, masculino, ["chicos"], ["boys"]).
sustantivo(plural, masculino, ["hermano"], ["brothers"]).
sustantivo(plural, masculino, ["edificios"], ["buildings"]).
sustantivo(plural, masculino, ["negocios"], ["business"]).
sustantivo(plural, femenino, ["llamadas"], ["calls"]).
sustantivo(plural, masculino, ["gatos"], ["cats"]).
sustantivo(plural, femenino, ["causas"], ["causes"]).
sustantivo(plural, masculino, ["centros"], ["centers"]).
sustantivo(plural, femenino, ["oportunidades"], ["chances"]).
sustantivo(plural, masculino, ["cambios"], ["changes"]).
sustantivo(plural, masculino, ["niños"], ["childs"]).
sustantivo(plural, masculino, ["niños"], ["childrens"]).
sustantivo(plural, femenino, ["iglesias"], ["churches"]).
sustantivo(plural, masculino, ["círculos"], ["circles"]).
sustantivo(plural, femenino, ["ciudades"], ["cities"]).
sustantivo(plural, femenino, ["clases"], ["classes"]).
sustantivo(plural, femenino, ["clases"], ["lessons"]).
sustantivo(plural, femenino, ["ropa"], ["clothes"]).
sustantivo(plural, masculino, ["colores"], ["colors"]).
sustantivo(plural, femenino, ["empresas"], ["companies"]).
sustantivo(plural, femenino, ["copias"], ["copies"]).
sustantivo(plural, masculino, ["países "], ["countries"]).
sustantivo(plural, masculino, ["cursos"], ["courses"]).
sustantivo(plural, femenino, ["vacas"], ["cows"]).
sustantivo(plural, masculino, ["días"], ["days"]).
sustantivo(plural, masculino, ["diccionarios"], ["dictionaries"]).
sustantivo(plural, femenino, ["direcciones"], ["directions"]).
sustantivo(plural, masculino, ["médicos"], ["doctors"]).
sustantivo(plural, femenino, ["puertas"], ["doors"]).
sustantivo(plural, femenino, ["hijas"], ["daughters"]).
sustantivo(plural, femenino, ["orejas"], ["ears"]).
sustantivo(plural, femenino, ["tierras"], ["lands"]).
sustantivo(plural, masculino, ["huevos"], ["eggs"]).
sustantivo(plural, femenino, ["manos"], ["hands"]).
sustantivo(plural, masculino, ["corazónes"], ["hearts"]).
sustantivo(plural, femenino, ["historias"], ["histories"]).
sustantivo(plural, masculino, ["caballos"], ["horses"]).
sustantivo(plural, femenino, ["horas"], ["hours"]).
sustantivo(plural, femenino, ["casas"], ["homes"]).
sustantivo(plural, femenino, ["hogares"], ["homes"]).
sustantivo(plural, femenino, ["ideas"], ["ideas"]).
sustantivo(plural, femenino, ["industrias"], ["industries"]).
sustantivo(plural, masculino, ["trabajos"], ["jobs"]).
sustantivo(plural, femenino, ["llaves"], ["keys"]).
sustantivo(plural, masculino, ["lenguajes"], ["lenguages"]).
sustantivo(plural, masculino, ["niveles"], ["levels"]).
sustantivo(plural, femenino, ["luces"], ["lights"]).
sustantivo(plural, femenino, ["listas"], ["lists"]).
sustantivo(plural, masculino, ["hombres"], ["mens"]).
sustantivo(plural, masculino, ["mapas"], ["maps"]).
sustantivo(plural, masculino, ["materiales"], ["materials"]).
sustantivo(plural, masculino, ["minutos"], ["minutes"]).
sustantivo(plural, masculino, ["meses"], ["months"]).
sustantivo(plural, femenino, ["noches"], ["nights"]).
sustantivo(plural, femenino, ["notas"], ["notes"]).
sustantivo(plural, masculino, ["soldados"], ["soldiers"]).
sustantivo(plural, femenino, ["soluciónes"], ["solutions"]).
sustantivo(plural, masculino, ["hijos"], ["sons"]).
sustantivo(plural, masculino, ["cuadrados"], ["squares"]).
sustantivo(plural, femenino, ["estrellas"], ["stars"]).
sustantivo(plural, masculino, ["estados"], ["states"]).
sustantivo(plural, femenino, ["paradas"], ["stops"]).
sustantivo(plural, femenino, ["calles"], ["streets"]).
sustantivo(plural, masculino, ["estudiantes"], ["students"]).
sustantivo(plural, masculino, ["climas"], ["climates"]).
sustantivo(plural, femenino, ["ventanas"], ["windows"]).
sustantivo(plural, femenino, ["mujeres"], ["women"]).
sustantivo(plural, femenino, ["palabras"], ["words"]).
sustantivo(plural, masculino, ["mundos"], ["worlds"]).
sustantivo(plural, masculino, ["años"], ["years"]).
sustantivo(plural, masculino, ["números"], ["numbers"]).
sustantivo(plural, masculino, ["objetos"], ["objects"]).
sustantivo(plural, femenino, ["oficinas"], ["offices"]).
sustantivo(plural, masculino, ["papeles"], ["papers"]).
sustantivo(plural, masculino, ["párrafos"], ["paragraphs"]).
sustantivo(plural, femenino, ["fiestas"], ["parties"]).
sustantivo(plural, femenino, ["personas"], ["persons"]).
sustantivo(plural, masculino, ["presidentes"], ["presidents"]).
sustantivo(plural, masculino, ["problemas"], ["problems"]).
sustantivo(plural, masculino, ["productos"], ["products"]).
sustantivo(plural, femenino, ["propiedades"], ["properties"]).
sustantivo(plural, femenino, ["preguntas"], ["questions"]).
sustantivo(plural, femenino, ["radios"], ["radios"]).
sustantivo(plural, femenino, ["razónes"], ["reasons"]).
sustantivo(plural, masculino, ["récords"], ["records"]).
sustantivo(plural, femenino, ["regiónes"], ["regions"]).
sustantivo(plural, masculino, ["anillos"], ["rings"]).
sustantivo(plural, masculino, ["ríos"], ["rivers"]).
sustantivo(plural, femenino, ["rocas"], ["rocks"]).
sustantivo(plural, femenino, ["reglas"], ["rules"]).
sustantivo(plural, femenino, ["escuelas"], ["schools"]).
sustantivo(plural, femenino, ["ciencias"], ["sciences"]).
sustantivo(plural, masculino, ["segundos"], ["seconds"]).
sustantivo(plural, femenino, ["frases"], ["sentences"]).
sustantivo(plural, femenino, ["hermanas"], ["sisters"]).
sustantivo(plural, femenino, ["tallas"], ["sizes"]).
sustantivo(plural, masculino, ["tamaños"], ["sizes"]).