/*
Código Fuente: sustantivosSingulares.pl
Desarrolado por: Saymon Astúa, Oscar Araya
Tarea 2 - Lenguajes
IS 2020 - Grupo 01

Descripción: Base de datos de los sustantivos en forma singular
Instituto Tecnológico de Costa Rica | CE3104 - Lenguajes, Compiladores e Interpretes
*/


/*sustantivo(singular, masculino, ["yo"], ["I"]).
sustantivo(singular, _, ["usted"], ["You"]).
sustantivo(singular, _, ["tú"], ["You"]).
sustantivo(singular, masculino, ["él"], ["He"]).
sustantivo(singular, femenino, ["ella"], ["She"]).
sustantivo(singular, _, ["lo"], ["It"]).
sustantivo(singular, _, ["eso"], ["It"]).
sustantivo(singular, _, ["se"], ["It"]).*/
sustantivo(singular, masculino, ["Prolog"], ["Prolog"]).
sustantivo(singular, masculino, ["uno"], ["one"]).
sustantivo(singular, masculino, ["sistema"], ["system"]).
sustantivo(singular, _, ["programación"], ["programming"]).
sustantivo(singular, femenino, ["demostración"], ["proving"]).
sustantivo(singular, femenino, ["comparación"], ["parse"]).
sustantivo(singular, masculino, ["análisis"], ["analysis"]).
sustantivo(singular, masculino, ["procesamiento"], ["processing"]).
sustantivo(singular, femenino, ["lógica"], ["logic"]).
sustantivo(singular, femenino, ["lingüística"], ["linguistics"]).
sustantivo(singular, femenino, ["inteligencia"], ["intelligence"]).
sustantivo(singular, femenino, ["edad"], ["age"]).
sustantivo(singular, masculino, ["aire"], ["air"]).
sustantivo(singular, masculino, ["animal"], ["animal"]).
sustantivo(singular, femenino, ["respuesta"], ["answer"]).
sustantivo(singular, femenino, ["manzana"], ["apple"]).
sustantivo(singular, femenino, ["naranja"], ["orange"]).
sustantivo(singular, masculino, ["arte"], ["art"]).
sustantivo(singular, masculino, ["bebé"], ["baby"]).
sustantivo(singular, femenino, ["bola"], ["ball"]).
sustantivo(singular, femenino, ["pelota"], ["ball"]).
sustantivo(singular, masculino, ["banco"], ["bank"]).
sustantivo(singular, femenino, ["cama"], ["bed"]).
sustantivo(singular, femenino, ["factura"], ["bill"]).
sustantivo(singular, masculino, ["pájaro"], ["bird"]).
sustantivo(singular, femenino, ["sangre"], ["blood"]).
sustantivo(singular, masculino, ["barco"], ["boat"]).
sustantivo(singular, masculino, ["cuerpo"], ["body"]).
sustantivo(singular, masculino, ["hueso"], ["bone"]).
sustantivo(singular, masculino, ["libro"], ["book"]).
sustantivo(singular, femenino, ["caja"], ["box"]).
sustantivo(singular, masculino, ["niño"], ["boy"]).
sustantivo(singular, masculino, ["hermano"], ["brother"]).
sustantivo(singular, masculino, ["edificio"], ["building"]).
sustantivo(singular, masculino, ["negocio"], ["deal"]).
sustantivo(singular, femenino, ["llamada"], ["call"]).
sustantivo(singular, femenino, ["capital"], ["capital"]).
sustantivo(singular, masculino, ["gato"], ["cat"]).
sustantivo(singular, femenino, ["causa"], ["cause"]).
sustantivo(singular, masculino, ["centro"], ["center"]).
sustantivo(singular, masculino, ["cambio"], ["change"]).
sustantivo(singular, masculino, ["niño"], ["child"]).
sustantivo(singular, femenino, ["iglesia"], ["church"]).
sustantivo(singular, masculino, ["círculo"], ["circle"]).
sustantivo(singular, femenino, ["ciudad"], ["city"]).
sustantivo(singular, femenino, ["clase"], ["class"]).
sustantivo(singular, femenino, ["ropa"], ["clothes"]).
sustantivo(singular, femenino, ["nube"], ["cloud"]).
sustantivo(singular, masculino, ["color"], ["color"]).
sustantivo(singular, femenino, ["empresa"], ["company"]).
sustantivo(singular, masculino, ["país "], ["country"]).
sustantivo(singular, masculino, ["curso"], ["course"]).
sustantivo(singular, femenino, ["vaca"], ["cow"]).
sustantivo(singular, masculino, ["día"], ["day"]).
sustantivo(singular, masculino, ["diccionario"], ["dictionary"]).
sustantivo(singular, femenino, ["dirección"], ["direction"]).
sustantivo(singular, femenino, ["dirección"], ["adress"]).
sustantivo(singular, femenino, ["distancia"], ["distance"]).
sustantivo(singular, femenino, ["puerta"], ["door"]).
sustantivo(singular, femenino, ["hija"], ["daughter"]).
sustantivo(singular, femenino, ["oreja"], ["ear"]).
sustantivo(singular, femenino, ["tierra"], ["earth"]).
sustantivo(singular, masculino, ["huevo"], ["egg"]).
sustantivo(singular, femenino, ["energía"], ["energy"]).
sustantivo(singular, masculino, ["ejemplo"], ["example"]).
sustantivo(singular, femenino, ["experiencia"], ["experience"]).
sustantivo(singular, masculino, ["ojo"], ["eye"]).
sustantivo(singular, masculino, ["material"], ["material"]).
sustantivo(singular, masculino, ["dinero"], ["money"]).
sustantivo(singular, masculino, ["número"], ["number"]).
sustantivo(singular, masculino, ["objeto"], ["object"]).
sustantivo(singular, femenino, ["fiesta"], ["party"]).
sustantivo(singular, masculino, ["pasado"], ["past"]).
sustantivo(singular, femenino, ["persona"], ["person"]).
sustantivo(singular, femenino, ["gente"], ["people"]).
sustantivo(singular, masculino, ["presidente"], ["president"]).
sustantivo(singular, masculino, ["problema"], ["problem"]).
sustantivo(singular, masculino, ["producto"], ["product"]).
sustantivo(singular, femenino, ["propiedad"], ["property"]).
sustantivo(singular, femenino, ["pregunta"], ["question"]).
sustantivo(singular, femenino, ["carrera"], ["race"]).
sustantivo(singular, femenino, ["radio"], ["radio"]).
sustantivo(singular, masculino, ["juego"], ["game"]).
sustantivo(singular, masculino, ["partido"], ["game"]).
sustantivo(singular, masculino, ["combustible"], ["fuel"]).
sustantivo(singular, masculino, ["combustible"], ["gas"]).
sustantivo(singular, femenino, ["chica"], ["girl"]).
sustantivo(singular, femenino, ["niña"], ["girl"]).
sustantivo(singular, masculino, ["vaso"], ["glass"]).
sustantivo(singular, masculino, ["vidrio"], ["glass"]).
sustantivo(singular, masculino, ["oro"], ["gold"]).
sustantivo(singular, masculino, ["grupo"], ["group"]).
sustantivo(singular, masculino, ["tamaño"], ["size"]).
sustantivo(singular, femenino, ["nieve"], ["snow"]).
sustantivo(singular, masculino, ["soldado"], ["soldier"]).
sustantivo(singular, femenino, ["solución"], ["solution"]).
sustantivo(singular, masculino, ["hijo"], ["son"]).
sustantivo(singular, femenino, ["parada"], ["stop"]).
sustantivo(singular, femenino, ["calle"], ["street"]).
sustantivo(singular, masculino, ["estudiante"], ["student"]).
sustantivo(singular, masculino, ["tiempo"], ["time"]).
sustantivo(singular, femenino, ["ventana"], ["window"]).
sustantivo(singular, femenino, ["mujer"], ["woman"]).
sustantivo(singular, femenino, ["palabra"], ["word"]).
sustantivo(singular, masculino, ["mundo"], ["world"]).
sustantivo(singular, masculino, ["año"], ["year"]).
sustantivo(singular, masculino, ["cabello"], ["hair"]).
sustantivo(singular, masculino, ["pelo"], ["hair"]).
sustantivo(singular, femenino, ["mano"], ["hand"]).
sustantivo(singular, masculino, ["corazón"], ["heart"]).
sustantivo(singular, masculino, ["calor"], ["heat"]).
sustantivo(singular, femenino, ["historia"], ["history"]).
sustantivo(singular, masculino, ["caballo"], ["horse"]).
sustantivo(singular, femenino, ["hora"], ["hour"]).
sustantivo(singular, femenino, ["casa"], ["home"]).
sustantivo(singular, femenino, ["hogar"], ["home"]).
sustantivo(singular, masculino, ["hielo"], ["ice"]).
sustantivo(singular, femenino, ["idea"], ["idea"]).
sustantivo(singular, femenino, ["información"], ["information"]).
sustantivo(singular, masculino, ["interés"], ["interest"]).
sustantivo(singular, masculino, ["hierro"], ["iron"]).
sustantivo(singular, masculino, ["trabajo"], ["job"]).
sustantivo(singular, femenino, ["llave"], ["key"]).
sustantivo(singular, femenino, ["tierra"], ["land"]).
sustantivo(singular, masculino, ["lenguaje"], ["lenguage"]).
sustantivo(singular, masculino, ["nivel"], ["level"]).
sustantivo(singular, masculino, ["hombre"], ["man"]).
sustantivo(singular, femenino, ["lluvia"], ["rain"]).
sustantivo(singular, femenino, ["razón"], ["reason"]).
sustantivo(singular, masculino, ["anillo"], ["ring"]).
sustantivo(singular, masculino, ["río"], ["river"]).
sustantivo(singular, femenino, ["roca"], ["rock"]).
sustantivo(singular, masculino, ["asiento"], ["seat"]).
sustantivo(singular, masculino, ["segundo"], ["second"]).
sustantivo(singular, femenino, ["frase"], ["sentence"]).
sustantivo(singular, femenino, ["hermana"], ["sister"]).
sustantivo(singular, femenino, ["talla"], ["size"]).